name: sristi_library
description: A simple library management app with barcode scanning and multi-language input
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  google_ml_kit: ^0.13.0
  flutter_barcode_scanner: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
