name: Flutter Android CI

on:
  push:
    branches:
      - main   # or 'master' or your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'

    - name: Get dependencies
      run: cd sristi_library && flutter pub get

    - name: Build APK
      run: cd sristi_library/sristi_library
flutter build apk --release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sristi_library-apk
        path: sristi_library/build/app/outputs/flutter-apk/app-release.apk
